### PR TITLE
Add unpurple filter based on github.com/mjambon/purple-fringe

### PR DESCRIPTION
**Pull request by solarsea**
Hi folks,

I've added a port of the github.com/mjambon/purple-fringe ocaml implementation to gmic. I often find it useful and having it available through the gmic toolkit certainly makes it easier to use.

Please review, I'm new to gmic.

Happy 2020
Stanislav

### CODE REVIEW

**Comment by Reptorian1125** [comment]
Even though I only did a initial test, I think this can be pushed with no changes. I should let you know that G'MIC supports dynamic GUI, and split preview.

Split preview command would contain something like _**gui_split_preview "something ${1--?}",${-3--1},**_ and dynamic gui would involve lines starting with something like u "{$1}"_. 1 in the end means disabled, 0 would be hidden while 2 is visible.

That's my review anyway.

**Comment by solarsea** [comment]
Thanks for the review, I've added them.

I still wonder if its possible to get the input bit depth in any way, before gmic converts it to its internal representation format.

Alternatively, I was thinking of adding another parameter to specify the input bit depth, with the special case of 0 for the current automatic max blue logic.

How do other commands handle concerns like this ?

**Comment by dtschump** [comment]
This looks good, thank you.
I'll probably remove the useless '-' signs in the front of each command.
I have also to add this new filter source for the update system.

**Comment by dtschump** [comment]
After further investigation... This looks **really** good! Thanks for this nice contribution !

**Comment by dtschump** [comment]
Filter is now available in 'Repair/'.
I've also published a Tweet about it: https://twitter.com/gmic_ip/status/1214091530153144320

Thanks again Stanislav.

**Pull request merged**
