### PR TITLE
Add (partial) french translation

### PR DESCRIPTION
**Pull request by cl4cnam**
This is just a partial french translation for the "Comic Book" filter.

### CODE REVIEW

**Comment by dtschump** [comment]
Hello. Unfortunately, this is not the preferred method to translate filters in the latest versions of G'MIC.
See : https://github.com/c-koi/gmic-qt/blob/master/translations/fr.ts
which is the French translation file that should be used instead.

**Comment by cl4cnam** [comment]
OK. Thank you. :)

**Comment by dtschump** [comment]
Sorry I put the wrong link in my previous post.
The correct link for translating filters is this one : https://github.com/c-koi/gmic-qt/blob/master/translations/filters/fr.ts

**Comment by cl4cnam** [comment]
Thank you :)

**Comment by cl4cnam** [comment]
Hello. I can't make the translation system work (French language). I've written an issue : [https://github.com/c-koi/gmic-qt/issues/121](https://github.com/c-koi/gmic-qt/issues/121).

**Comment by cl4cnam** [comment]
Hello. The issue is fixed. :)

I have two questions :
1. Can I test my modifications without recompile Gmic ?
2. How can I specify that in the "Comic Book" filter, "Light" should be translated into "Légère" and not "Lumière" as in the "Tune HSV Colors" filter ?

**Comment by dtschump** [comment]
Hello @cl4cnam . Sorry for the late response, but we have actually thought a lot about this issue.
Indeed, the current system did not take the possible fact that two identical strings in different filters had to be translated differently (word 'Light' is a very good example you exhibited).

We are then setting up a new translation layer to be able to deal with these cases. Basically, this means translations won't be performed directly in the `.ts` file anymore, but in a `.csv` file that allows to define such exceptions.
Here is a link to the french translation file I've started : https://github.com/dtschump/gmic/blob/develop/resources/gmic_qt_fr.csv

It's a simple array of strings (that can be imported in libreoffice for instance), with these properties:
- A,string in first column corresponds to an original string in English (main strings of all filters have been automatically imported).
- The second column contains the translated strings (here, in French).

Now, if you have an "exception" for one filter, then you can just put the concerned filter name in the third column.
If you have more than one filter concerned, just use the columns after.
This way, we will be able to have different French translations for the same English term.

This should be more simple to deal with that tabular file.

**Comment by dtschump** [comment]
Also note that the strings are sorted by decreasing occurence, so translating the first strings will benefit for more filters.
I'm currently doing a bit of translation work right now. I'll test later tonight with the plug-in.

**Comment by cl4cnam** [comment]
Hello. Thank you very much! :)

**Comment by dtschump** [comment]
Dear @cl4cnam ,

The french translation file has been moved to the gmic-community repository, here : 

https://github.com/dtschump/gmic-community/blob/master/translations/gmic_qt_fr.csv

Do not hesitate to create PR with corrections and new translations. This file will be automatically used to generate the French translation of the G'MIC-Qt plug-in at each release.
I'm planning to release G'MIC 3.0.0 hopefully before the end of the week ;)

**Comment by cl4cnam** [comment]
Hello @dtschump. Sorry for not having reacted. I waited for new commits in "https://github.com/dtschump/gmic".
I know how to compile G'Mic from "https://github.com/dtschump/gmic" and "https://github.com/c-koi/gmic-qt" but I don't know how to integrate "https://github.com/dtschump/gmic-community".
Therefore, I don't know how to test https://github.com/dtschump/gmic-community/blob/master/translations/gmic_qt_fr.csv.
Thank you! :)

**Comment by cl4cnam** [comment]
I'm very sorry :( but my PC is indeed too old for compiling G'Mic :(
So, I just gave the modified "gmic_qt_fr.csv" without having tested it! :(

**Comment by dtschump** [comment]
Thanks !
I've made a single commit from your PR : https://github.com/dtschump/gmic-community/commit/c948d5deba29ad6a360475ac502944b7f98ce524

**Comment by cl4cnam** [comment]
Thank you! :)

**Pull request closed without merging**
