### PR TITLE
Updates to joan_rake.gmic

### PR DESCRIPTION
**Pull request by ornithologistnightmare**
'JR' here, finally got back to GH. Haven't really used this for a long time. Here's the contents of my G'MIC file with some updates to various filters.

### CODE REVIEW

**Comment by dtschump** [comment]
Please do not re-define commands or filters that already exist. It will mainly cause compatibility issues with the commands and filters located in the G'MIC stdlib, which is not desirable.

**Comment by ornithologistnightmare** [comment]
I've tried to make these modified filters 'backwards compatible' but I can change their names.

**Comment by dtschump** [comment]
Yes please, usually it is suggested to add a short prefix corresponding to your name/pseudo to your custom command names, like `jr_deform` (instead of `deform`). It is unique and easy to know where it has been defined.

**Comment by ornithologistnightmare** [comment]
Forgot to say that I've sorted it out now. I might work on some Cubehelix filter if someone else hasn't done so when I get up.

**Pull request merged**
