### PR TITLE
a new filter ("Comic Book")

### PR DESCRIPTION
**Pull request by cl4cnam**
This filter is presented in http://gimpchat.com/viewtopic.php?f=11&t=19335&p=266517#p266512 .
It's a "photo to cartoon" filter.

### CODE REVIEW

**Comment by dtschump** [comment]
I will check when I return from vacations. Thanks.

**Comment by cl4cnam** [comment]
Ok, good vacation! :)

**Comment by Reptorian1125** [comment]
Just from a quick look, it doesn't look suitable for processing  multiple images. repeat $! l[$>] endl done below the main variables should solve that part, and in case of multiple output per layer, then use '$<' instead.

**Comment by dtschump** [comment]
A few remarks:
- Name of author / date of filter creation is missing, something as:
~~~~
#@gui : note = note("<small>Author: <i>FirstName Name</i>.      Latest Update: <i>2021/08/29</i>.</small>")
~~~~
- Labels and parameter names are not capitalized (see https://capitalizemytitle.com/ for help doing that). This is actually done automatically by the filter updater, but if this can be done by the filter author, it's way better (avoid warnings during filter update).
- As noticed by @Reptorian1125 , filter does not work with multiple layers. Using a construct such as:
~~~~
repeat $! l[$>]
  .. filter code for a single image ...
endl done
~~~~
will solve this issue.

If you don't know how to do this, please tell us, maybe we can have a look at it later.

**Comment by dtschump** [comment]
Looks good!

**Comment by dtschump** [comment]
Merged, and added a preview splitting modes.

**Comment by cl4cnam** [comment]
Thanks! :)

**Comment by dtschump** [comment]
Someone has already recorded a video about this filter :)

https://www.youtube.com/watch?v=YGjcfiL1WpY

**Comment by cl4cnam** [comment]
Thanks for the news! :)

**Pull request merged**
