### PR TITLE
Another one

### PR DESCRIPTION
**Pull request by ornithologistnightmare**
In future I don't think that I should make more of these pull requests because it would be better for you to make changes to the G'MIC files that I send in case something's not quite right (though the 'allow edits from maintainers' option might fix that) - that, and I also need to keep up with the commits and if you push another one before I submit my request, I have to merge in the  new changes to the proper repo and sort everything out again.

### CODE REVIEW

**Comment by ornithologistnightmare** [comment]
Thanks, I have made more updates to my commands already. What's the best way forward? I don't think I should be given write access to the main repo since I'm inexperienced. Since I've already got some important updates to my .gmic file sitting on my computer, should I create another request after merging everything into my fork?

**Comment by dtschump** [comment]
I guess the best way is for you to create pull requests regularly, and keep your repo being synchronized with the official `gmic-community` repo (I guess this should be easy to do so, from the github interface, not sure though).

**Comment by ornithologistnightmare** [comment]
I'll continue with the current workflow. Also (I'd ask on discuss.pixls.us but I've forgotten my password again and the reset mail isn't sending) can there be an option to get u() to include or exclude the minimum and maximum values in the range so that there isn't that one-in-a-million chance of a value that would get rounded up? I don't know if it already does that.

**Comment by dtschump** [comment]
For the `u()`, I don't really get your point, why not specifying an acceptable value as a bound then. For instance, if you don't want `x in ]0,1[` , just do `x in [epsilon,1-epsilon]` with `epsilon` small enough.

**Comment by ornithologistnightmare** [comment]
That works. I'm working on something to do with that and I'll try to sort out the CubeHelix command. The latter's a difficult one to figure out. I still haven't got the reset email; I'll try again tomorrow.

**Pull request merged**
